site_name: C# Notes
nav:
  - Home: index.md
  - Naming Convention: naming-conventions.md
  - Access Modifiers: access-modifiers.md
  - Implementing a Class: implementing-a-class.md
  - Files: files.md
  - Interface: interface.md
  - .Net CLI: dot-net.md
theme:
  name: material
  palette:
    primary: "purple"
    accent: "orange"
markdown_extensions:
  - codehilite:
      guess_lang: false
      pygments_style: "emacs"
      use_pygments: true
      lang_guess: false
      css_class: "highlight"
      noclasses: true
      hl_lines: ''
      linenums: false
      langs:
        - csharp