site_name: C# Notes
nav:
  - Home: index.md
  - Access-Modifiers: access-modifiers.md
  - Files: files.md
  - Interface: interface.md
  - .Net CLI: dot-net.md
theme:
  name: material
  palette:
    primary: "purple"
    accent: "orange"
  font:
    text: "Roboto"
    code: "Roboto Mono"